name: Packer

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'ModConfigs/**'  
  workflow_call:
    secrets:
      MODRINTH_TOKEN:
        required: true

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init Resourcepack
        run: |
          mkdir -p pack/assets/VaultPatcher
          cp -r ModConfigs/*/* pack/assets/VaultPatcher/
      
      - name: Add mcmeta
        run: |
          cat <<EOL >> pack/pack.mcmeta
          {
            "pack": {
              "pack_format": 18,
              "description": "VPGS库的简体中文硬编码汉化数据包"
            }
          }
          EOL

      - name: Pack Up!
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = 'pack'
            output_file_path = '/tmp/pack.zip'

      - name: Setup custom info
        id: info
        run: |
          current_date=$(date +%G%m%d)
          sha_short=$(git rev-parse --short HEAD)
          git_commit=$(git show -s --format=%s)
          echo "version=$current_date-$sha_short" >> "$GITHUB_OUTPUT"
          echo "commit=$git_commit" >> "$GITHUB_OUTPUT"

      - name: Testing Info
        run: |
          echo "Version = ${{ steps.info.outputs.version }}"
          echo "Changelog = ${{ steps.info.outputs.commit }}"

      - name: Release publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: IDWIdXwS
          modrinth-unfeature-mode: subset
          name: VP-test2
          version: ${{ steps.info.outputs.version }}
          version-type: release
          changelog: |
            ${{ steps.info.outputs.commit }}

            ------
            由 [GitHub Action][github-action] 上传

            [github-action]: https://github.com/features/actions
          loaders: minecraft
          game-versions: |
            >=1.16.5
          files: /tmp/pack.zip
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
